server:
        host: 0.0.0.0
        port: 8088
        server_list_file_path: "/opt/tulc/serverlist"
partner_api:
        uri: "https://svrapi-tulc.mto.zing.vn/getCCU"
        secret_key: "tqkJ8kX2SBhme7rH"
        timeout: 30
        concurrent: 10
